- name: Run Duo install as part of Host configuration for User Mgmt
  hosts: control-center
  become: true
  become_method: sudo

  vars:
      duo_env_path: 'ansible-control-center/config/generated/post-vm-creation/duo.env'
      state_file: 'ansible-control-center/config/generated/post-vm-creation/vm.state'
      duo_ikey: "{{ lookup('env','duo_ikey') }}"
      duo_skey: "{{ lookup('env','duo_skey') }}"
      duo_api_host: "{{ lookup('env','duo_api_host') }}"
      duo_pam_groups: ['deployer', 'sudo']
      duo_pam_prompts: 3
      add_user_groups_list:
          - name: deployer
      add_users_list:
          - name: "{{ lookup('env','cec_user') }}"
      ssh_key: "{{ lookup('env','ssh_key') }}"

  pre_tasks:
      - name: Display State File
        shell: 'cat {{ state_file }} '
        register: state_file_output

      - debug: var=state_file_output.stdout

      - name: Source env file content
        shell: '. ./{{ duo_env_path }} && env'
        register: env_file_result

      - name: Provision Users
        template:
            src: vars/users.j2
            dest: vars/users.yml
            owner: root
            group: root
            mode: 0644

  roles:
      - role: ansible-users
      - role: ansible-duo_install
