---
- name: Configure control-center
  hosts: vms
  become: true
  become_method: sudo

  tasks:
      - name: Add Ansible inventory mappings to /etc/hosts
        blockinfile:
            path: /etc/hosts
            block: |
                {% for host in groups['vms'] | difference(['localhost']) %}
                {{ hostvars[host].ansible_ssh_host }} {{ host }}
                {% endfor %}
