---
- name: Configure control-center
  hosts: control-center

  vars:
      USER_HOME: '/home/ubuntu'

  tasks:
      - name: Copy Generated duo.env playbbok to Host
        tags: duo_env_transfer
        ansible.builtin.copy:
            src: '../../config/generated/pre-vm-creation/duo.env'
            dest: '{{ USER_HOME }}/ansible-control-center/config/generated/pre-vm-creation/duo.env'
