---
- hosts: master
  become: yes
  tasks:
    - name: Execute the command in remote shell
      ansible.builtin.shell: cat /etc/rancher/k3s/k3s.yaml > /tmp/k3s.yaml
    - name: Fetch k3s.yaml from master to control-center 
      ansible.builtin.fetch:
        src: /tmp/k3s.yaml
        dest: /tmp/
    - name: Ping all Hosts
      ansible.builtin.ping:
    - name: Get IP Address of k3s-master
      ansible.builtin.shell: ansible-inventory  --host k3s-master | jq -r '.ansible_ssh_host' > /tmp/k3s-master-ip
    - name: Configure k3s.yaml 
      ansible.builtin.shell: sed -i '' "s/127.0.0.1/$(cat k3s-master-ip)/" /tmp/k3s-master/tmp/k3s.yaml
    - name: Copy k3s.yaml to config
      ansible.builtin.copy: 
        src: /tmp/k3s-master/tmp/k3s.yaml
        dest: /home/ubuntu/ansible-control-center/config/generated/post-vm-creation
