---
- hosts: master
  become: yes
  tasks:
    - name: Execute the command in remote shell
      ansible.builtin.shell: cat /etc/rancher/k3s/k3s.yaml > /tmp/k3s.yaml
    - name: Fetch k3s.yaml from master to control-center 
      ansible.builtin.fetch:
        src: /tmp/k3s.yaml
        dest: /tmp/
  
- hosts: control-center
  tasks:
    - name: Copy k3s.yaml to config
      ansible.builtin.copy: 
        src: /tmp/k3s-master/tmp/k3s.yaml
        dest: /home/ubuntu/ansible-managed/k3s.yaml
    - name: Configure k3s.yaml 
      ansible.builtin.shell: sed -i "s/127.0.0.1/k3s-master/" /home/ubuntu/ansible-managed/k3s.yaml
    - name: Set KUBECONFIG Environment 
      lineinfile: 
        dest=/home/ubuntu/.bashrc 
        line='export KUBECONFIG=$HOME/ansible-managed/k3s.yaml' 
        insertafter='EOF' 
        state=present


