---
- name: Linux Reboot
  hosts: vms
  gather_facts: no
  become: true
  become_method: sudo

  tasks:
      - name: Reboot the machine (Wait for 5 min)
        reboot:
            reboot_command: reboot userspace
            boot_time_command: uptime | cut -d ' ' -f 5
            reboot_timeout: 300
