---
- hosts: control-center

  vars:
    awsvault_app: aws-vault
    awsvault_version: 6.3.1
    awsvault_osarch: linux-amd64
    awsvault_dl_url: https://github.com/99designs/{{ awsvault_app }}/releases/download/v{{ awsvault_version }}/{{ awsvault_app }}-{{ awsvault_osarch }}
    awsvault_bin_path: /usr/local/bin
    awsvault_file_mode: '0755'

  roles:
      - darkwizard242.awsvault
