---
- name: Run Duo install as part of Host configuration for User Mgmt
  hosts: control-center
  become: true
  become_method: sudo

  vars:
      # Setup details for DUO
      duo_ikey: "{{ lookup('env','duo_ikey') }}"
      duo_skey: "{{ lookup('env','duo_skey') }}"
      duo_api_host: "{{ lookup('env','duo_api_host') }}"
      duo_pam_groups: ["deployer","sudo"]
      duo_pam_prompts: 3

      users_group_add_list:
          - name: deployer
            groups: [ "sudo" ]

      users_add_list:
          - name: "{{ lookup('env','cec_user') }}"
            groups: [ "deployer" ]
            unlimited_superuser: true
            ssh_key: _SSH_KEY_

  roles:
      - role: ansible-users
      - role: ansible-duo_install
